In [5]:
import pandas as pd

In [6]:
df = pd.read_csv("/content/drive/MyDrive/datasets/Gapminder.csv", error_bad_lines=False, sep=";")

In [7]:
df.head()

       country continent  year  lifeExp       pop   gdpPercap
0  Afghanistan      Asia  1952   28.801   8425333  779.445314
1  Afghanistan      Asia  1957   30.332   9240934  820.853030
2  Afghanistan      Asia  1962   31.997  10267083  853.100710
3  Afghanistan      Asia  1967   34.020  11537966  836.197138
4  Afghanistan      Asia  1972   36.088  13079460  739.981106

In [8]:
df = df.rename(columns={"country":"Pais", "continent":"continente", "year":"Ano", "lifeExp":"Expectativa de Vida", "pop":"Pop Total", "gdpPercap":"PIB"})

In [9]:
df.head(10)

          Pais continente   Ano  Expectativa de Vida  Pop Total         PIB
0  Afghanistan       Asia  1952               28.801    8425333  779.445314
1  Afghanistan       Asia  1957               30.332    9240934  820.853030
2  Afghanistan       Asia  1962               31.997   10267083  853.100710
3  Afghanistan       Asia  1967               34.020   11537966  836.197138
4  Afghanistan       Asia  1972               36.088   13079460  739.981106
5  Afghanistan       Asia  1977               38.438   14880372  786.113360
6  Afghanistan       Asia  1982               39.854   12881816  978.011439
7  Afghanistan       Asia  1987               40.822   13867957  852.395945
8  Afghanistan       Asia  1992               41.674   16317921  649.341395
9  Afghanistan       Asia  1997               41.763   22227415  635.341351

In [10]:
df.shape

(3312, 6)

In [11]:
df.columns

Index(['Pais', 'continente', 'Ano', 'Expectativa de Vida', 'Pop Total', 'PIB'], dtype='object')

In [12]:
df = df.rename(columns={"country":"Pais", "continent":"Continente", "year":"Ano", "lifeExp":"Expectativa de Vida", "pop":"Pop Total", "gdpPercap":"PIB"})

In [14]:
df["continente"].unique()

array(['Asia', 'Europe', 'Africa', 'Americas', nan, 'FSU', 'Oceania'],
      dtype=object)

In [16]:
Oceania =df.loc[df["continente"]== "Oceania"]
Oceania.head(10)

     Pais continente   Ano  Expectativa de Vida  Pop Total          PIB
975  Fiji    Oceania  1962               56.494     421869  2039.393277
976  Fiji    Oceania  1967               58.607     485000  2170.073285
977  Fiji    Oceania  1972               60.642     544000  2797.759484
978  Fiji    Oceania  1977               62.669     599339  3182.569600
979  Fiji    Oceania  1982               64.683     658906  3209.257468
980  Fiji    Oceania  1987               66.626     719574  2974.850227
981  Fiji    Oceania  1992               66.575     750242  3410.286040
982  Fiji    Oceania  1997               66.836     797890  3643.629208
983  Fiji    Oceania  2002               67.832     856346  4004.481972
984  Fiji    Oceania  2007               68.774     918675  4118.158294

In [17]:
df.groupby("continente")["Pais"].nunique()

continente
Africa      51
Americas    25
Asia        41
Europe      35
FSU          6
Oceania      3
Name: Pais, dtype: int64

In [18]:
df.groupby("Ano")["Expectativa de Vida"].mean()

Ano
1950    62.002568
1951    65.904167
1952    49.206867
1953    66.674563
1954    67.459817
1955    67.806757
1956    67.950637
1957    51.614590
1958    68.815936
1959    68.226579
1960    68.470837
1961    68.862480
1962    54.035234
1963    69.595735
1964    70.063105
1965    70.259881
1966    70.447526
1967    56.263629
1968    70.689081
1969    70.653896
1970    70.961141
1971    71.103976
1972    58.474481
1973    71.500338
1974    71.778504
1975    71.939218
1976    72.158050
1977    60.429090
1978    72.717567
1979    73.018717
1980    73.064524
1981    73.337399
1982    62.365871
1983    73.787778
1984    74.100741
1985    74.112222
1986    74.452222
1987    63.984860
1988    74.760000
1989    74.924444
1990    74.283437
1991    74.374848
1992    65.008443
1993    74.324545
1994    74.456667
1995    74.552727
1996    75.029394
1997    65.873799
1998    75.569697
1999    75.703636
2000    76.026364
2001    76.257879
2002    66.835695
2003    76.586667
2004    76.921563
2005    76.718667
2006    77.887778
2007    67.868557
Name: Expectativa de Vida, dtype: float64